HasinduNiran/Vehicle_Service_Management_System

Backend/Models/Feedback.js
Backend/Routes/Feedback_Route.js
Backend/index.js

Feedback yenu

---

client/src/App.jsx
client/src/assets/pages/Feedback/CreateFeedback.jsx
client/src/assets/pages/Feedback/DeleteFeedback.jsx
client/src/assets/pages/Feedback/EditFeedbck.jsx
client/src/assets/pages/Feedback/ReadOneFeedback.jsx
client/src/assets/pages/Feedback/ShowAllFeedback.jsx
client/src/assets/pages/Home.jsx

Show all feedback

---

Backend/Routes/Feedback_Route.js
client/src/assets/pages/Feedback/ShowAllFeedback.jsx

SearchBar Feedback

---

client/src/assets/pages/Home.jsx

Reverts HasinduNiran/Vehicle_Service_Management_System#62

Revert "Update Home.jsx"

---

client/src/assets/pages/Home.jsx

Reverts HasinduNiran/Vehicle_Service_Management_System#66

Revert "homeeeeee"

---

Backend/Routes/Inventory_Route.js
client/src/assets/pages/Inventory/ShowInventory.jsx

SearchBar Inventory

---

Backend/Routes/Inventory_Route.js
client/src/assets/pages/Inventory/ShowInventory.jsx

Reverts HasinduNiran/Vehicle_Service_Management_System#57

Revert "SearchBar Inventory"

---

Backend/Models/ServiceHistory.js
Backend/Routes/ServiceHistory_Route.js
Backend/Routes/Vehicle_Route.js
client/src/App.jsx
client/src/assets/pages/SPackage/ShowPackage.jsx
client/src/assets/pages/ServiceHistory/CreateServiceHistory.jsx
client/src/assets/pages/ServiceHistory/EditServiceHistory.jsx
client/src/assets/pages/ServiceHistory/ReadOneServiceHistory.jsx
client/src/assets/pages/ServiceHistory/ShowAllServiceHistory.jsx
client/src/assets/pages/Vehicle/CreateVehicle.jsx
client/src/assets/pages/Vehicle/DeleteVehicle.jsx
client/src/assets/pages/Vehicle/ReadOneVehicle.jsx
client/src/assets/pages/Vehicle/ShowVehicle.jsx

get employee data to service 

---

client/src/assets/pages/Booking/ShowAllBooking.jsx

search function added

---

client/src/App.jsx
client/src/assets/pages/Inventory/AddItemPage.jsx
client/src/assets/pages/Inventory/ReadOneInventory.jsx
client/src/assets/pages/Inventory/RetrieveItemPage.jsx
client/src/assets/pages/Inventory/ShowInventory.jsx

when you press the retrieve button, inventory automatically decreese and save in DB

Retrieve inventory items

---

Backend/Models/Booking.js
client/src/assets/pages/Booking/CreateBooking.jsx
client/src/assets/pages/Booking/ShowAllBooking.jsx

add booking id and cus id

---

client/src/assets/pages/Feedback/CreateFeedback.jsx

Reverts HasinduNiran/Vehicle_Service_Management_System#115

Revert not creating  "Feedback yenura 1"

---

Backend/Models/Booking.js
Backend/Routes/Booking_Route.js
client/src/assets/pages/Booking/CreateBooking.jsx
client/src/assets/pages/Booking/ShowAllBooking.jsx

select package aded

---

Backend/Models/Booking.js
Backend/Routes/Booking_Route.js
client/src/assets/pages/Booking/CreateBooking.jsx
client/src/assets/pages/Booking/ShowAllBooking.jsx

sevices add kra

---

client/src/assets/pages/Booking/CreateBooking.jsx

geted data from customer

---

Backend/Models/Booking.js
client/src/assets/pages/Booking/CreateBooking.jsx

remove model requered part and add frontend validation

remove model requered part and add frontend validation

---

Backend/Models/ServiceHistory.js
Backend/Routes/ServiceHistory_Route.js
client/src/assets/pages/ServiceHistory/CreateServiceHistory.jsx
client/src/assets/pages/ServiceHistory/EditServiceHistory.jsx
client/src/assets/pages/ServiceHistory/ShowAllServiceHistory.jsx

add search with date and other field,
special function done

Special fun hasindu add to main

---

client/src/App.jsx
client/src/assets/components/ManagerLogin.jsx
client/src/assets/pages/Booking/BookingDashBoard.jsx
client/src/assets/pages/Booking/DeleteBooking.jsx
client/src/assets/pages/Booking/ReportBookings.jsx

created a dashboard

---

client/src/App.jsx
client/src/assets/pages/Booking/AdminCreateBooking.jsx
client/src/assets/pages/Booking/BookingDashBoard.jsx
client/src/assets/pages/Booking/CreateBooking.jsx
client/src/assets/pages/Booking/EditBooking.jsx
client/src/assets/pages/Booking/ReadOneBooking.jsx

edit and admin create tika haduwa (dashboard)

edit and admin create tika haduwa (dashboard)

---

client/src/assets/pages/Booking/AdminCreateBooking.jsx
client/src/assets/pages/Booking/BookingDashBoard.jsx
client/src/assets/pages/Booking/CreateBooking.jsx
client/src/assets/pages/Booking/ReportBookings.jsx
client/src/assets/pages/Booking/ShowAllBooking.jsx

validation add kra, report genaration ekath tikak wenas kra

validation add kra

---

client/src/assets/pages/Inventory/CreateInventory.jsx
client/src/assets/pages/Inventory/EditInventory.jsx
client/src/assets/pages/Inventory/ReadOneInventory.jsx

Inventory eke edit ekat validations add kraa.(Hodaid description ek)

validations added

---

client/src/assets/pages/Inventory/DeleteInventory.jsx
client/src/assets/pages/Inventory/EditInventory.jsx

frontend validations

---

client/src/assets/pages/Customer/CreateCustomer.jsx
client/src/assets/pages/Customer/CustomerDashboard.jsx
client/src/assets/pages/Customer/DeleteCustomer.jsx
client/src/assets/pages/Customer/ReadOneCustomer.jsx
client/src/assets/pages/Customer/ShowCustomer.jsx
client/src/assets/pages/Customer/UpdateCustomer.jsx

Reverts HasinduNiran/Vehicle_Service_Management_System#181

Revert "modified"

---

client/src/assets/pages/Customer/CreateCustomer.jsx
client/src/assets/pages/Customer/CustomerDashboard.jsx
client/src/assets/pages/Customer/ReadOneCustomer.jsx

added validations to updateCustome.jsx and changed delete id to cusID

validations,id changing

---

Backend/Models/Booking.js
client/src/assets/pages/Booking/AdminCreateBooking.jsx
client/src/assets/pages/Booking/BookingDashBoard.jsx
client/src/assets/pages/Booking/CreateBooking.jsx
client/src/assets/pages/Booking/EditBooking.jsx

add some changes

---

Backend/Routes/BookingLimit_Route.js

available bookings frontend eke pennana widiyata haduwa

available bookings frontend eke pennana widiyata haduwa

---

Backend/Routes/BookingLimit_Route.js
Backend/Routes/Booking_Route.js
client/src/App.jsx
client/src/assets/pages/Booking/BookingDashBoard.jsx
client/src/assets/pages/Booking/BookingLimitDashBoard.jsx
client/src/assets/pages/Booking/DeleteBookingLimit.jsx
client/src/assets/pages/Booking/EditBookingLimit.jsx

edit booking limit and, delete bookking limit added

edit booking limit and, delete bookking limit added
